services:
  db:
    image: postgres:16-alpine
    container_name: sta_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-smarttransport}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-smarttransport}
      POSTGRES_DB: ${POSTGRES_DB:-smarttransport}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-smarttransport}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [sta_net]

  redis:
    image: redis:7-alpine
    container_name: sta_redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redisdata:/data
    networks: [sta_net]

  backend:
    build: ./backend
    container_name: sta_backend
    restart: unless-stopped
    ports: 
      - "8000:8000"
    volumes:
       - cachedata:/code/cache_data
    env_file: .env
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks: [sta_net]
  sta_osrm:
    image: osrm/osrm-backend
    container_name: sta_osrm
    restart: unless-stopped
    command: osrm-routed --algorithm mld /data/ile-de-france-latest.osrm
    volumes:
      - /root/osrm-data:/data
    networks: [sta_net]
    expose:
      - "5000"
    healthcheck:
      test: ["CMD-SHELL", "timeout 3 bash -c '</dev/tcp/localhost/5000' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 180s

  autoheal:
    image: willfarrell/autoheal
    container_name: sta_autoheal
    restart: unless-stopped
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    networks: [sta_net]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  frontend:
    build: ./frontend
    container_name: sta_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      API_INTERNAL_URL: http://backend:8000
      NEXT_PUBLIC_API_URL: http://195.110.34.127:8000/api/v1
    depends_on: [backend]
    networks: [sta_net]

  nginx:
    image: nginx:1.27-alpine
    container_name: sta_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - certbot_www:/var/www/certbot:ro
    depends_on: [backend, frontend]
    networks: [sta_net]

volumes:
  pgdata:
  redisdata:
  certbot_www:
  cachedata:

networks:
  sta_net:
    driver: bridge
